name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  token:
    runs-on: ubuntu-22.04
    steps:
      - name: Get JQ and curl
        run: |
          sudo apt-get install -y jq curl
      - name: Get token
        run: |
          curl --request POST \
          --data '{\
            "role_id": "'"${VAULT_APPROLE_ROLE_ID}"'",\
            "secret_id": "'"${VAULT_APPROLE_SECRET_ID}"'"}' \
            http://wallpi:8200/v1/auth/github-runners/login \
            | jq -r '.auth.client_token' > token
      - name: Set VAULT_TOKEN
        run: |
          echo "VAULT_TOKEN=$(cat token)" >> GITHUB_ENV
  validate:
    strategy:
      matrix:
        example:
          - simple
    name: validate
    runs-on: ubuntu-22.04
    env:
      CONSUL_HTTP_ADDR: "bare.brucellino.github.beta.tailscale.net:8500"
    steps:
      - name: Tailscale GPG key
        run: curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      - name: Add Tailscale repo config
        run: curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      - name: Install tailscale
        run: sudo apt-get update ; sudo apt-get install -y tailscale
      - name: Join Tailnet
        run: sudo tailscale up  --authkey ${{ secrets.TS_KEY }}
      - name: Checkout code
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: Get Terraform
        run: |
          curl -fSL https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip \
          | gunzip -> terraform ; chmod u+x terraform
      - name: Init terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} init
      - name: Validate terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} validate
  plan:
    strategy:
      matrix:
        example:
          - simple
    name: plan
    needs:
      - validate
    runs-on: ubuntu-22.04
    env:
      CONSUL_HTTP_ADDR: "bare.brucellino.github.beta.tailscale.net:8500"
      VAULT_ADDR: "wallpi.brucellino.github.beta.tailscale.net:8200"
    steps:
      - name: Tailscale GPG key
        run: curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      - name: Add Tailscale repo config
        run: curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      - name: Install tailscale
        run: sudo apt-get update ; sudo apt-get install -y tailscale
      - name: Join Tailnet
        run: sudo tailscale up  --authkey ${{ secrets.TS_KEY }}
      - name: Checkout code
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: Get Terraform
        run: |
          curl -fSL https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip \
          | gunzip -> terraform ; chmod u+x terraform
      - name: Init terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} init
      - name: Validate terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} validate
      - name: Create workspace (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./terraform workspace select ${{ github.event.pull_request.number }} ||\
          ./terraform workspace new ${{ github.event.pull_request.number }}
      - name: Create workspace (main)
        if: ${{ github.event_name == 'push' && github.ref == 'main' }}
        run: |
          ./terraform workspace select main || \
          ./terraform workspace new main
      - name: Plan
        run: ./terraform -chdir=examples/${{ matrix.example }} plan
      - name: apply
        run: echo "not implemented yet"
  release:
    needs:
      - plan
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -D '@semantic-release/commit-analyzer' \
          '@semantic-release/release-notes-generator' \
          '@semantic-release/changelog' \
          'semantic-release-license' \
          '@semantic-release/github'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
